---
dist: trusty

branches:
  only:
    - master

env:
  - distribution: rpi-raspbian
    version: stretch

before_install:
  - sudo apt-get --yes --no-install-recommends install binfmt-support qemu-user-static
  - echo ':arm:M::\x7fELF\x01\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x28\x00:\xff\xff\xff\xff\xff\xff\xff\x00\xff\xff\xff\xff\xff\xff\xff\xff\xfe\xff\xff\xff:/usr/bin/qemu-arm-static:' | sudo tee -a /proc/sys/fs/binfmt_misc/register
  - 'sudo docker pull balenalib/${distribution}:${version}'
  - 'sudo docker build --no-cache --rm --file=.travis/Dockerfile.${distribution}-${version} --tag=${distribution}-${version}:ansible .travis'

script:
  - 'container_id=$(mktemp)'
  - 'sudo docker run --hostname rpi-test-build --detach --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro --volume="${PWD}":/etc/ansible:ro ${distribution}-${version}:ansible > "${container_id}"'
  - 'sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook -v /etc/ansible/tests/test.yml --syntax-check'
  - 'sudo docker exec "$(cat ${container_id})" env ANSIBLE_FORCE_COLOR=1 ansible-playbook -v /etc/ansible/tests/test.yml -i /etc/ansible/tests/inventory --skip-tags "reboot,hostname,swap,travis"'
  - 'sudo docker exec "$(cat ${container_id})" id -u alex | grep -q "no" && (echo "user not found" && exit 1) || (echo "user alex found" && exit 0)'
  - 'sudo docker exec "$(cat ${container_id})" id -u pi | grep -q "no" && (echo "pi user found" && exit 1) || (echo "pi user not found" && exit 0)'
  - 'sudo docker exec "$(cat ${container_id})" /usr/bin/kubectl > /dev/null && (echo "kubectl is installed" && exit 0) || (echo "kubectl is not installed or in the path" && exit 1)'
  - 'sudo docker rm -f "$(cat ${container_id})"'
