---
dist: trusty

language: python
python: "2.7"

# Doc: https://docs.travis-ci.com/user/customizing-the-build#Build-Matrix
env:
  - ANSIBLE_VERSION=latest
branches:
  only:
    - master

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install python-apt
  - sudo useradd pi --password raspberry
  - docker --version
  - sudo mkdir -p /etc/systemd/system/getty.target.wants
  - touch ~/getty-test-service
  - sudo ln -s ~/getty-test-service /etc/systemd/system/getty.target.wants/getty@tty1.service

install:
  # Install Ansible.
  - if [ "$ANSIBLE_VERSION" = "latest" ]; then pip install ansible; else pip install ansible==$ANSIBLE_VERSION; fi
  - if [ "$ANSIBLE_VERSION" = "latest" ]; then pip install ansible-lint; fi

script:
  # Check the role/playbook's syntax.
  - ansible-playbook -i tests/inventory tests/test.yml --syntax-check

  # Run all ansible roles
  - ansible-playbook -i tests/inventory tests/test.yml --skip-tags "upgrade, reboot, swap"

  # Check if alex user is created
  - id -u alex | grep -q "no" && (echo "user not found" && exit 1) || (echo "user alex found" && exit 0)

  # check if pi user is deleted
  - id -u pi | grep -q "no" && (echo "user not found" && exit 0) || (echo "user pi found" && exit 1)

  # check if alex has sudo
  - sudo su - alex -c "sudo ls" && (echo "user alex has sudo" && exit 0) || (echo "user alex cannot sudo" && exit 1)

  # check if docker is the correct version
  - docker --version | grep -q "18.06" && (echo "docker is running 18.06" && exit 0) || (echo "docker is not running 18.06" && exit 1)

  # check if kubectl is installed
  - kubectl > /dev/null && (echo "kubectl is installed" && exit 0) || (echo "kubectl is not installed or in the path" && exit 1)

