apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: pihole-deployment
spec:
  selector:
    matchLabels:
      app: pihole
  replicas: 1
  template:
    metadata:
      labels:
        app: pihole
    spec:
      containers:
      - name: pihole
        image: pihole/pihole:latest
        env:
          - name: ServerIP
            value: "${IP}"
          - name: ServerIPv6
            value: "${IPv6}"
        ports:
        - containerPort: 80
        - containerPort: 443
        - containerPort: 67
        - containerPort: 53