- name: disable autologin
  file:
    src: /lib/systemd/system/getty@.service
    dest: /etc/systemd/system/getty.target.wants/getty@tty1.service
    state: link
    force: yes

- name: reboot server
  command: /sbin/shutdown -r +1 "Ansible gets rid of pi"
  delegate_to: "{{ inventory_hostname }}"
  tags: ['reboot']

- name: waiting for sever to come back
  wait_for:
    port: 22
    host: "{{ ansible_host }}"
    search_regex: OpenSSH
    delay: 65
  connection: local
  tags: ['reboot']

- name: delete pi user
  user:
    name: pi
    state: absent
