---
- name: debug
  block:
  - name: test data node selection
    file:
      path: /home/alex/success
      state: touch
    when: ansible_hostname in k3s_data_nodes

  - name: end play
    meta: end_play
    when: end_after_debug

  when: debug

- name: install glusterfs
  apt:
    name: gluster
