- name: apt | update keys
  command: apt-key update

- name: apt | apt-get update
  apt:
    update_cache: yes

- name: apt | ensure common packages
  apt:
    name: "{{ query('flattened','{{ rasbpi_common_packages }}') }}"
    state: latest
    update_cache: yes
    cache_valid_time: 3600

- name: apt | update and upgrade packages
  apt:
    upgrade: dist
    update_cache: yes
    cache_valid_time: 3600

- name: ensure hostname
  hostname:
    name: "{{ inventory_hostname }}"

- name: setup /etc/hosts
  template:
    src: hosts.j2
    dest: /etc/hosts
    backup: yes

- name: disable leds
  command: "{{ item }}"
  with_items:
    - echo none > /sys/class/leds/led0/trigger
  ignore_errors: True
