- name: create user
  user:
    name: alex
    groups: sudo
    state: present

- name: ensure ssh keys are on hosts
  authorized_key:
    user: alex
    state: present
    key: "{{ lookup('file', '/Users/alex/.ssh/id_rsa_amerenda_personal.pub') }}" 

- name: ensure sudo group to have passwordless sudo
  lineinfile:
    dest: /etc/sudoers
    state: present
    regexp: '^%sudo'
    line: '%sudo ALL=(ALL) NOPASSWD: ALL'
    backup: yes

- name: check sudoers file
  command: visudo -c
  register: sudo_result
