---
- name: disable swap
  command: "{{ item }}"
  with_items:
    - dphys-swapfile swapoff
    - dphys-swapfile uninstall
    - update-rc.d dphys-swapfile remove
  tags: ['swap']

- name: check for cgroups
  command: "grep 'cgroup_enable=cpuset' /boot/cmdline.txt"
  register: _grep_result
  ignore_errors: True

- name: add cgroups
  shell: echo $( cat /boot/cmdline.txt ) "cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory" >  /boot/cmdline.txt
  when: _grep_result.rc != 0

- name: reboot pis
  command: /sbin/shutdown -r +1 "Ansible adds cgroups"
  delegate_to: "{{ inventory_hostname }}"
  tags: ['reboot']

- name: waiting for sever to come back
  wait_for:
    port: 22
    host: "{{ ansible_host }}"
    search_regex: OpenSSH
    delay: 65
  connection: local
  tags: ['reboot']

